config/routes.rb
Rails.application.routes.draw do
  authenticate :person, -> person { person.email == ENV['ADMIN_EMAIL'] } do
    mount_avo at: '/avo'
  end

  root "main_page#index"
  
  get "event_list" => "main_page#event_list"
  get "map" => "main_page#map"
  
  devise_for :people
  devise_for :organizations
  
  resources :organizations, except: [:new, :create] do
    resources :events
    resource :accreditation, only: :show
  end

  resources :people, except: [:new, :create] do
    resources :notifications, only: [:index, :destroy]
  end
  resources :friendships, only: [:create, :destroy]
  resources :participants, only: [:create, :update, :destroy]
  resource :starred_organizations, only: [:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  INFO = 'info'
  INVITE = 'invite'
  OFFER = 'offer'
  WARNING = 'warning'

  belongs_to :person
  belongs_to :author, polymorphic: true
  belongs_to :target, polymorphic: true

  enum :notice_type, [INFO, INVITE, OFFER, WARNING].index_with(&:itself)

  scope :unread, -> { where(read: false) }

  validates :text, :author_id, :author_type, :target_type, :notice_type, presence: true
  validates :read, inclusion: [true, false]
end

app/controllers/avo/notifications_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
module Avo
  class NotificationsController < Avo::ResourcesController
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  include Pagy::Backend
  include Authenticator

  before_action :authenticate_user

  # rubocop:disable Rails::SkipsModelValidations
  after_action { @notifications&.update_all(read: true) }
  # rubocop:enable Rails::SkipsModelValidations

  def index
    person = Person.find(params[:person_id])
    @pagy, @notifications = pagy(person.notifications.includes(:author).order(created_at: :desc))
  end

  def destroy
    Notification.find(params[:id]).destroy
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def author_name(notification)
    author = notification.author
    return 'Не удалось установить автора' if author.nil?

    if notification.author.is_a?(Person)
      link_to author.full_name, person_path(author)
    else
      link_to author.name, organization_path(author)
    end
  end
end

app/views/notifications/_invite.html.erb
<div class="flex justify-end px-8 mt-2">
    <%= link_to organization_event_path(notification.target.organization, notification.target), class: 'blue-btn' do %>
        <svg class="svg-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M18 14v4.833A1.166 1.166 0 0 1 16.833 20H5.167A1.167 1.167 0 0 1 4 18.833V7.167A1.166 1.166 0 0 1 5.167 6h4.618m4.447-2H20v5.768m-7.889 2.121 7.778-7.778" />
        </svg>
        <span>Показать</span>
    <% end %>

    <% if current_person.events.include?(notification.target) %>
        <%= render partial: 'participants/destroy_button', locals: { participant: notification.target.participants.find_by(person: current_person) } %>
    <% else %>
        <%= render partial: 'participants/create_button', locals: { event: notification.target } %>
    <% end %>
</div>

app/views/notifications/_notification.html.erb
<tr id="nid_<%= notification.id %>" class="relative transform scale-100 text-xs py-1 border-b-2 border-gray-100 cursor-default <%= 'bg-gray-200 bg-opacity-25' if notification.read? %>">
  <td class="pl-5 pr-3 whitespace-no-wrap">
    <div class="text-gray-800 text-base"><%= notification.created_at.strftime('%d.%m.%Y') %></div>
    <div class="text-sm"><%= notification.created_at.strftime('%H:%M') %></div>
  </td>

  <td class="px-2 py-2 whitespace-no-wrap flex justify-between">
    <div>
      <div class="leading-5 text-gray-500 text-base font-medium"><%= author_name(notification) %></div>
      <div class="leading-5 text-gray-800 text-base mt-2"><%= notification.text %></div>
    </div>

    <% if !notification.read? %>
      <% if notification.notice_type == 'invite' %>
        <%= render partial: 'invite', locals: { notification: } %>

      <% elsif notification.notice_type == 'offer' %>

        <%= render partial: 'offer', locals: { notification: } %>
      <% end %>
    <% end %>

    <%= button_to person_notification_path(current_person, notification), method: :delete, data: { turbo: true }, onclick: "this.form.requestSubmit(); $('#nid_#{notification.id}').remove();", class: 'flex items-center bg-gray-800 hover:bg-gray-950 text-gray-100 px-4 py-2 rounded text-sm space-x-2 transition duration-100' do %>
      <svg class="w-6 h-6 text-white " aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z" />
      </svg>
    <% end %>
  </td>
</tr>

app/views/notifications/_offer.html.erb
<div class="flex justify-end px-8 mt-2">
    <%= render partial: 'friendship/buttons', locals: { person: notification.target } %>
</div>

app/views/notifications/index.html.erb
<% content_for :title, 'Нотификации' %>

<div class="w-full">
  <div class="py-8 sm:py-16 block lg:py-24 relative bg-opacity-50 z-40">
    <div class="relative mx-auto h-full pb-20 md:pb-10 sm:max-w-xl md:max-w-full lg:max-w-screen-xl">

      <div class="mx-auto max-w-7xl relative">
        <div class="max-w-xl mx-auto text-center mb-4">
          <div class="inline-flex px-4 py-1.5 mx-auto rounded-full">
            <p class="text-4xl font-semibold tracking-widest text-g uppercase">Нотификации</p>
          </div>
        </div>

        <% if @notifications.present? %>
          <div class="w-full h-full overflow-auto shadow bg-white" id="journal-scroll">
            <table class="w-full">
              <tbody class="">
                <%= render partial: 'notification', collection: @notifications %>
              </tbody>
            </table>
        <% else %>
          <div class="max-w-xl mx-auto text-center text-base mt-8">
              Нотификаций пока нет
          </div>
        <% end %>
      </div>
    </div>

    <%= render partial: 'layouts/pagy_down_bar' %>
  </div>
</div>