config/routes.rb
Rails.application.routes.draw do
  authenticate :person, -> person { person.email == ENV['ADMIN_EMAIL'] } do
    mount_avo at: '/avo'
  end

  root "main_page#index"
  
  get "event_list" => "main_page#event_list"
  get "map" => "main_page#map"
  
  devise_for :people
  devise_for :organizations
  
  resources :organizations, except: [:new, :create] do
    resources :events
    resource :accreditation, only: :show
  end

  resources :people, except: [:new, :create] do
    resources :notifications, only: [:index, :destroy]
  end
  resources :friendships, only: [:create, :destroy]
  resources :participants, only: [:create, :update, :destroy]
  resource :starred_organizations, only: [:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_taggable_on :tags

  SRID = 4326

  mount_uploader :image, ImageUploader

  belongs_to :organization
  has_many :participants, dependent: :delete_all
  has_many :people, through: :participants

  has_many :notice_targets, as: :target, dependent: :nullify, class_name: 'Notification'

  validates :name, :start_date, :end_date, presence: true
  validates :online, inclusion: [true, false]
end

app/controllers/avo/events_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
module Avo
  class EventsController < Avo::ResourcesController
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_organization

  def show
    @event = @organization.events.find(params[:id])
    @participant = Participant.find_by(person: current_person, event: @event)
  end

  def new
    @event = @organization.events.new
  end

  def edit
    @event = @organization.events.find(params[:id])
  end

  def create
    @event = @organization.events.new(event_params)
    @event.tag_list = event_tags if params[:event][:tag_list].present?

    if @event.save
      redirect_to organization_event_path(@organization, @event), notice: 'Событие успешно создано'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @event = @organization.events.find(params[:id])
    @event.tag_list = event_tags if params[:event][:tag_list].present?

    if @event.update(event_params)
      redirect_to organization_event_path(@organization, @event), notice: 'Событие успешно обновлено',
                                                                  status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy!
    redirect_to events_path, notice: 'Событие полностью удалено ', status: :see_other
  end

  private

  def set_organization
    @organization = Organization.find(params.expect(:organization_id))
  end

  def event_params
    data = params.expect(event: %i[name description image start_date end_date online])
    location = RGeo::Cartesian.factory(srid: Event::SRID).point(*params[:event][:location].split)

    data.merge({ location: })
  end

  def event_tags
    params[:event][:tag_list].split(',').map { _1.strip.downcase }.compact_blank
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def dates(event)
    [event.start_date.strftime('%d.%m.%Y'), event.end_date.strftime('%d.%m.%Y')].join(' - ')
  end

  def time(event)
    [event.start_date.strftime('%H:%M'), event.end_date.strftime('%H:%M')].join(' - ')
  end

  def online(event)
    event.online ? '(Онлайн)' : '(Офлайн)'
  end
end

app/views/events/_buttons.html.erb
<% if current_person.events.include?(event) %>
    <%= render partial: 'participants/destroy_button', locals: { participant: participant } %>
<% else %>
    <%= render partial: 'participants/create_button', locals: { event: event } %>
<% end %>

<% if current_person.friends.present? %>
    <%= form_with scope: :participants, url: participants_path, class: 'grid mx-4' do |form| %>
        <%= form.select :person_id, options_from_collection_for_select(current_person.friends, :id, :full_name), {}, { id: 'tom-select-it', class: 'mt-4 input-group' } %>
        <%= form.text_field :event_id, value: event.id, class: 'hidden', readonly: true %>
        <%= form.check_box :accepted, class: 'hidden', readonly: true, checked: false %>
        <%= form.submit 'Пригласить друга', data: { turbo: true }, class: 'mt-2 blue-btn' %>
    <% end %>
<% end %>

app/views/events/_card.html.erb
<%= link_to organization_event_path(card.organization.id, card), data: { turbo: false }, class: 'transition-all duration-1000 bg-white hover:bg-blue-500 hover:shadow-xl mt-2 relative z-40 group' do %>

    <div class="py-2 px-9 relative">
        <% if card.tag_list.present? %>
            <div class="absolute top-0 right-2 z-10 mt-3 ml-3">
                <%= render partial: 'events/tag', collection: card.tag_list %>
            </div>
        <% end %>

        <%= image_tag card.image_url %>

        <h3 class="mt-8 text-lg font-semibold text-black group-hover:text-white">
            <%= card.name %>
        </h3>

        <p class="mt-2 text-base text-gray-600 group-hover:text-white">
            <%= card.start_date.strftime('%d.%m.%Y %H:%M') %>
        </p>

        <p class="mt-2 text-base text-gray-600 group-hover:text-white">
            <%= card.organization.name %>
        </p>

        <p class="mt-4 text-base text-gray-600 group-hover:text-white">
            <%= truncate(card.description, length: 120) %>
        </p>
    </div>
<% end %>

app/views/events/_tag.html.erb
<span class="inline-flex select-none rounded-sm bg-indigo-200 px-2 py-1 text-xs font-semibold text-indigo-900"><%= tag %></span>

app/views/events/edit.html.erb
<% content_for :title, "Редактирование #{@event.name}" %>

<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css">
<%= javascript_include_tag 'new_event_map' %>

<div class="md:w-2/3 w-full">
  <div class="h-full w-full">

    <%= form_with(model: @event, class: 'flex h-full items-center contents p-5', url: organization_event_path(@organization, @event)) do |form| %>
      <% if @event.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
          <h2><%= pluralize(@event.errors.count, 'error') %> prohibited this event from being saved:</h2>

          <ul class="list-disc ml-6">
            <% @event.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="bg-stone-100 sm:w-[80%] w-[90%] mx-auto p-6">
        <div class="p-5 mt-5">
          <div class="md:p-5 p-1 sm:mt-1 mt-1">
            <div class="mt-5">
              <%= form.label :name, 'Название', class: 'text-xl' %>
              <%= form.text_field :name, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>
          </div>

          <div class="md:p-5 p-1 initials flex md:flex-row flex-col justify-between">
            <div class="mt-5 mr-4">
              <%= form.label :start_date, 'Дата начала', class: 'text-xl' %>
              <%= form.text_field :start_date, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>

            <div class="mt-5">
              <%= form.label :end_date, 'Дата окончания', class: 'text-xl' %>
              <%= form.text_field :end_date, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>
          </div>

          <div class="md:p-5 p-1 sm:mt-1 mt-1">
            <div class="mt-5">
              <%= form.label :tag_list, 'Теги (через запятую)', class: 'text-xl' %>
              <%= form.text_field :tag_list, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>
          </div>

          <div class="md:p-5 p-1 sm:mt-1 mt-1">
            <div class="mt-5">
              <%= form.label :description, 'Описание', class: 'text-xl' %>
              <%= form.textarea :description, rows: 4, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>

            <div class="mt-5">
              <%= form.label :image, 'Изображение', class: 'text-xl' %>
              <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg', class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>
          </div>

          <div class="btn mt-2 w-[100%] bg-transparent flex items-center">
            <%= form.submit 'Обновить событие', class: 'black-btn' %>
            <%= link_to 'Назад', organization_event_path(@organization, @event), class: 'black-btn' %>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/events/new.html.erb
<% content_for :title, 'Новое мероприятие' %>

<%= javascript_include_tag 'new_event_map' %>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css">

<div class="grid grid-cols-2">
  <div class="h-full w-full">

    <%= form_with(model: @event, class: 'flex h-full items-center contents p-5', url: organization_events_path(@organization)) do |form| %>
      <% if @event.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
          <h2><%= pluralize(@event.errors.count, 'error') %> prohibited this event from being saved:</h2>

          <ul class="list-disc ml-6">
            <% @event.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="bg-stone-100 w-full mx-auto p-6">
        <div class="p-5">
          <div class="p-5">
            <%= form.label :name, 'Название', class: 'text-xl' %>
            <%= form.text_field :name, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
          </div>

          <div class="md:p-5 p-1 initials flex lex-row justify-between">
            <div class="mt-5">
              <%= form.label :start_date, 'Дата начала', class: 'text-xl' %>
              <%= form.text_field :start_date, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>

            <div class="mt-5 mx-4">
              <%= form.label :end_date, 'Дата окончания', class: 'text-xl' %>
              <%= form.text_field :end_date, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>

            <div class="mt-auto mb-2">
              <%= form.checkbox :online, class: 'peer hidden' %>
              <%= form.label :online, 'Онлайн', class: 'select-none cursor-pointer rounded-lg border-2 border-gray-400 py-3 px-6 font-bold text-gray-600 transition-colors duration-200 ease-in-out peer-checked:bg-indigo-200 peer-checked:text-indigo-900 peer-checked:border-indigo-200' %>
            </div>
          </div>

          <div class="md:p-5 p-1 sm:mt-1 mt-1">
            <div class="mt-5">
              <%= form.label :tag_list, 'Теги (через запятую)', class: 'text-xl' %>
              <%= form.text_field :tag_list, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>
          </div>

          <div class="md:p-5 p-1 sm:mt-1 mt-1">
            <div class="mt-5">
              <%= form.label :description, 'Описание', class: 'text-xl' %>
              <%= form.textarea :description, rows: 4, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>

            <div class="mt-5">
              <%= form.label :image, 'Изображение', class: 'text-xl' %>
              <%= form.file_field :image, accept: 'image/png,image/gif,image/jpeg', class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
            </div>

            <div class="mt-5">
              <%= form.label :location, 'Расположение', class: 'text-xl' %>
              <%= form.text_field :location_name, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @event.errors[:description].none?, "border-red-400 focus:outline-red-600": @event.errors[:description].any? }] %>
              <%= form.text_field :location, class: 'hidden', readonly: true %>
            </div>
          </div>

          <div class="btn mt-2 w-[100%] bg-transparent flex items-center">
            <%= form.submit 'Создать событие', class: 'black-btn' %>
            <%= link_to 'Назад', organization_path(@organization), class: 'black-btn' %>
          </div>
        </div>
      </div>
    <% end %>

  </div>

  <div class="p-5">
    <div class="h-full">
      <div id="map" class="map w-full h-full"></div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% content_for :title, @event.name %>

<link href="https://cdn.jsdelivr.net/npm/tom-select@2.4.3/dist/css/tom-select.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/tom-select@2.4.3/dist/js/tom-select.complete.min.js"></script>

<div class="w-full">
  <section class=" bg-blue-500ray-50">
    <div class="py-8 sm:py-16 block lg:py-24 relative bg-opacity-50 z-40">

      <div class="relative mx-auto h-full px-4 pb-20 md:pb-10 sm:max-w-xl md:max-w-full md:px-24">

        <div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8 relative">
          <div class="grid grid-cols-2 gap-20">
            <div class="max-w-xl mx-auto text-center">

              <div class="px-4 py-1.5 mx-auto rounded-full">
                <p class="text-4xl font-semibold tracking-widest text-g"><%= @event.name %></p>
                <p class="text-base leading-relaxed text-gray-600 group-hover:text-white">
                  Участников: <%= @event.participants.accepted.size %>
                </p>
                <%= link_to @organization.name, organization_path(@organization), class: 'text-base leading-relaxed group-hover:text-white' %>
              </div>

              <p class="mt-4 text-base leading-relaxed text-gray-600 group-hover:text-white">
                <%= dates(@event) %> <br>
                <%= time(@event) %> <br>
                <%= online(@event) %>
              </p>

              <p class="my-4 text-base leading-relaxed text-gray-600 group-hover:text-white">
                <%= @event.description %>
              </p>

              <% if organization_signed_in? && current_organization == @organization %>
                <%= link_to 'Редактировать', edit_organization_event_path(@organization, @event), class: 'white-btn' %>
              <% end %>

              <% if person_signed_in? %>
                <%= render partial: 'buttons', locals: { event: @event, participant: @participant } %>
              <% end %>
            </div>

            <div>
              <%= image_tag @event.image_url %>
            </div>

            <% if @event.tag_list.present? %>
              <div class="absolute top-0 right-2 z-10 mt-3 ml-3">
                <%= render partial: 'events/tag', collection: @event.tag_list %>
              </div>
            <% end %>
          </div>

          <div class="max-w-xl mx-auto my-14 text-center">
          </div>
        </div>
      </div>
    </section>
  </div>

<script>
    new TomSelect('#tom-select-it', {
      plugins: ['dropdown_input'],
      maxItems: 1,
    });
</script>