config/routes.rb
Rails.application.routes.draw do
  authenticate :person, -> person { person.email == ENV['ADMIN_EMAIL'] } do
    mount_avo at: '/avo'
  end

  root "main_page#index"
  
  get "event_list" => "main_page#event_list"
  get "map" => "main_page#map"
  
  devise_for :people
  devise_for :organizations
  
  resources :organizations, except: [:new, :create] do
    resources :events
    resource :accreditation, only: :show
  end

  resources :people, except: [:new, :create] do
    resources :notifications, only: [:index, :destroy]
  end
  resources :friendships, only: [:create, :destroy]
  resources :participants, only: [:create, :update, :destroy]
  resource :starred_organizations, only: [:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/person.rb
class Person < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :followers, class_name: 'Friendship', foreign_key: 'author_id', inverse_of: :author, dependent: :delete_all
  has_many :followers_people, through: :followers, source: :author
  has_many :following, class_name: 'Friendship', foreign_key: 'follower_id',
                       inverse_of: :follower, dependent: :delete_all
  has_many :following_people, through: :following, source: :follower
  has_many :participants, dependent: :delete_all
  has_many :events, through: :participants

  has_many :notifications, dependent: :delete_all

  has_many :authored_notifications, as: :author, dependent: :nullify, class_name: 'Notification'
  has_many :notice_targets, as: :target, dependent: :nullify, class_name: 'Notification'

  has_many :starred_organizations, dependent: :delete_all

  validates :first_name, :last_name, :email, presence: true

  def full_name
    [first_name, last_name].compact.join(' ')
  end

  def request_friends_for_person
    Person.where(id: followers.or(following).where(not_approved: self).pluck(:author_id, :follower_id)).where.not(id:)
  end

  def request_friends_from_person
    Person
      .where(id: followers.or(following).where.not(not_approved: [nil, id]).pluck(:author_id, :follower_id))
      .where.not(id:)
  end

  def friends
    Person
      .where(id: followers.or(following).where(not_approved_id: nil).pluck(:author_id, :follower_id).flatten.uniq)
      .where.not(id:)
  end

  def friend?(person)
    friends.exists?(id: person.id)
  end

  def accepted_events
    events.joins(:participants).where(participants: { accepted: true })
  end

  def starred?(organization_id)
    starred_organizations.select(:organization_id).exists?(organization_id:)
  end
end

app/controllers/avo/people_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
module Avo
  class PeopleController < Avo::ResourcesController
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  include Pagy::Backend
  include Authenticator

  before_action :authenticate_user
  before_action :set_person, only: %i[edit update destroy]

  def index
    people = if params[:friends].present?
               Person.find(params[:friends]).friends
             else
               Person.all
             end

    if params[:person_name].present?
      people = people.where("concat(first_name, ' ', last_name) ILIKE ?", ['%', params[:person_name], '%'].join)
    end

    @pagy, @people = pagy(people)
  end

  def show
    @person = Person.includes(:followers_people, :following_people).find(params.expect(:id))
    part = visible_events(@person).joins(:event).order('events.start_date')

    @pagy, @participants = pagy(part, limit: 10)
  end

  def events
    @person = Person.find(params.expect(:id))

    @pagy, @events = pagy(@person.events.order(:start_date), limit: 10)
    render partial: 'events'
  end

  def edit; end

  def update
    if @person.update(person_params)
      redirect_to @person, notice: 'Данные профиля успешно обновлены', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @person.destroy!
    redirect_to people_path, notice: 'Профиль был полностью удален', status: :see_other
  end

  private

  def set_person
    @person = Person.find(params.expect(:id))
  end

  def person_params
    params.expect(person: %i[first_name last_name avatar birthday description city])
  end

  def visible_events(person)
    return person.participants if person == current_person
    return person.participants.public_or_normal_visible if person.friend?(current_person)

    person.participants.public_visible
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def years_old(person)
    return if person.birthday.nil?

    [Date.current.year - person.birthday.year, 'лет'].join(' ')
  end

  def name_and_years(person)
    [person.full_name, years_old(person)].compact.join(', ')
  end
end

app/views/people/profile/_buttons.html.erb
<%= link_to edit_person_path(person), class: 'blue-btn' do %>
    <svg class="svg-icon" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 13v-2a1 1 0 0 0-1-1h-.757l-.707-1.707.535-.536a1 1 0 0 0 0-1.414l-1.414-1.414a1 1 0 0 0-1.414 0l-.536.535L14 4.757V4a1 1 0 0 0-1-1h-2a1 1 0 0 0-1 1v.757l-1.707.707-.536-.535a1 1 0 0 0-1.414 0L4.929 6.343a1 1 0 0 0 0 1.414l.536.536L4.757 10H4a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h.757l.707 1.707-.535.536a1 1 0 0 0 0 1.414l1.414 1.414a1 1 0 0 0 1.414 0l.536-.535 1.707.707V20a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-.757l1.707-.708.536.536a1 1 0 0 0 1.414 0l1.414-1.414a1 1 0 0 0 0-1.414l-.535-.536.707-1.707H20a1 1 0 0 0 1-1Z" />
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z" />
    </svg>
    <span>Редактировать</span>
<% end %>

<%= button_to 'Выйти', destroy_person_session_path,
    method: :delete,
    class: 'rose-btn' %>

app/views/people/profile/_events.html.erb
<%= turbo_frame_tag 'person_events' do %>

    <div class="relative">
        <% if @pagy.pages > 1 &&  @pagy.page != 1 %>
            <a href="/people/<%= @person.id %>?page=<%= @pagy.page - 1 %>" aria-label="Next">
                <svg class="w-6.5 h-6.5 text-black" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v13m0-13 4 4m-4-4-4 4" />
                </svg>
            </a>
        <% else %>
            <div class="w-6.5 h-6.5"></div>
        <% end %>

        <div class="absolute h-full border border-dashed border-opacity-20 border-secondary ml-3"></div>

        <%= render partial: 'people/profile/participation', collection: @participants, locals: { person: @person } %>
    </div>

    <% if @pagy.pages > 1 && @pagy.page != @pagy.pages %>
        <a href="/people/<%= @person.id %>?page=<%= @pagy.page + 1 %>" aria-label="Next">
            <svg class="w-6.5 h-6.5 text-black" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19V5m0 14-4-4m4 4 4-4" />
            </svg>
        </a>
    <% else %>
        <div class="w-6.5 h-6.5"></div>
    <% end %>
<% end %>

app/views/people/profile/_participation.html.erb
<!-- start::Timeline item -->
<div class="flex items-center w-full my-2 py-2 hover:bg-gradient-to-r from-white via-gray-200 to-white">
    <div class="w-1/12 z-10">
        <% if participation.public_visible? %>
            <%= render partial: 'people/profile/visible_icons/public_visible_icon', locals: { participant: participation } %>
        <% elsif participation.private_visible? %>
            <%= render partial: 'people/profile/visible_icons/private_visible_icon', locals: { participant: participation } %>
        <% else %>
            <%= render partial: 'people/profile/visible_icons/normal_visible_icon', locals: { participant: participation } %>
        <% end %>
    </div>

    <div class="w-11/12 flex justify-between">
        <div>
            <%= link_to participation.event.name, organization_event_path(participation.event.organization, participation.event), data: { turbo: false }, class: 'text-sm' %>
            <p class="text-xs text-gray-500"><%= participation.event.start_date %></p>
        </div>

        <div class="flex">
            <% if person_signed_in? %>
                <% if current_person == @person %>
                    <%= form_with scope: :participants, url: participant_path(participation), method: :put, data: { turbo_frame: "visible_#{participation.id}" } do |form| %>
                        <%= form.select(:visible, [['всем', 'public'], ['друзьям', 'normal'], ['никому', 'private']], { selected: participation.visible }, onchange: 'this.form.requestSubmit();') %>
                    <% end %>
                <% end %>

                <% if current_person.events.include?(participation.event) %>
                    <%= render partial: 'participants/destroy_button', locals: { participant: participation } %>
                <% else %>
                    <%= render partial: 'participants/create_button', locals: { event: participation.event } %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>
<!-- end::Timeline item -->