config/routes.rb
Rails.application.routes.draw do
  authenticate :person, -> person { person.email == ENV['ADMIN_EMAIL'] } do
    mount_avo at: '/avo'
  end

  root "main_page#index"
  
  get "event_list" => "main_page#event_list"
  get "map" => "main_page#map"
  
  devise_for :people
  devise_for :organizations
  
  resources :organizations, except: [:new, :create] do
    resources :events
    resource :accreditation, only: :show
  end

  resources :people, except: [:new, :create] do
    resources :notifications, only: [:index, :destroy]
  end
  resources :friendships, only: [:create, :destroy]
  resources :participants, only: [:create, :update, :destroy]
  resource :starred_organizations, only: [:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/organization.rb
class Organization < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  mount_uploader :logo, LogoUploader

  has_many :events, dependent: :destroy
  has_many :authored_notifications, as: :author, dependent: :nullify, class_name: 'Notification'

  has_many :starred_organizations, dependent: :delete_all

  validates :email, :name, presence: true
  validates :accredited, inclusion: [true, false]
end

app/controllers/avo/organizations_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/3.0/controllers.html
module Avo
  class OrganizationsController < Avo::ResourcesController
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  include Pagy::Backend

  before_action :set_organization, only: %i[edit update destroy]
  before_action :authenticate_organization!, only: %i[edit update destroy]

  def index
    organizations = find_organization
    organizations = select_favorite_organizations(organizations) if params[:favorite] == 'true'

    @pagy, @organizations = pagy(organizations)
  end

  def show
    @organization = Organization.includes(:events).find(params[:id])

    @pagy, @events = pagy(@organization.events.order(created_at: :desc), limit: 9)
  end

  def edit; end

  def update
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Организация успешно обновлена', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @organization.destroy!
    redirect_to organizations_path, notice: 'Организация была полностью удалена', status: :see_other
  end

  private

  def set_organization
    @organization = Organization.find(params.expect(:id))
  end

  def organization_params
    params.expect(organization: %i[name description activity_field logo])
  end

  def find_organization
    if params[:organization_name]
      Organization.where('name ILIKE ?', "%#{params[:organization_name]}%")
    else
      Organization.all
    end
  end

  def select_favorite_organizations(organizations)
    fav_ids = []

    fav_ids += cookies[:starred_organizations].gsub(/[0-9]*/).compact_blank if cookies[:starred_organizations].present?

    if person_signed_in?
      fav_ids += current_person.starred_organizations.select(:organization_id).pluck(:organization_id)
    end

    organizations.where(id: fav_ids)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  include Pagy::Frontend
end

app/views/organizations/_buttons.html.erb
<% if current_organization.accredited? %>
    <%= link_to 'Добавить мероприятие', new_organization_event_path(organization),
    class: 'white-btn' %>
<% else %>
    <%= link_to 'Пройти аккредитацию', organization_accreditation_path(organization),
    class: 'border-2 border-red-400 px-4 py-2 font-semibold bg-red-200 rounded-lg hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline' %>
<% end %>

<%= link_to 'Редактировать', edit_organization_path(organization),
    class: 'white-btn' %>

<%= button_to 'Выйти', destroy_organization_session_path,
    method: :delete,
    class: 'mt-4 border-2 border-gray-500 px-4 py-2 font-semibold bg-gray-300 rounded-lg hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline' %>

app/views/organizations/_card.html.erb
<%= link_to organization_path(card),
            class: 'bg-white hover:bg-blue-500 hover:shadow-xl m-2 p-4 relative z-40 group' do %>

  <div class="py-2 px-9 relative">
    <%= image_tag card.logo_url %>

    <h3 class="mt-8 text-lg font-semibold text-black group-hover:text-white">
      <%= card.name %>
    </h3>

    <p class="mt-4 text-base text-gray-600 group-hover:text-white">
      <%= truncate(card.description, length: 120) %>
    </p>
  </div>
<% end %>

app/views/organizations/_labels.html.erb
<% if !organization.accredited? %>
    <div id="not_accredited" class="bg-red-700 rounded-full h-5 w-5" title="Организация не подтверждена">
    <svg class="text-gray-100 h-5 w-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M6 18 17.94 6M18 18 6.06 6" />
    </svg>
    </div>
<% end %>

<% if !organization_signed_in? %>
    <% if cookies[:starred_organizations]&.include?(".#{organization.id}.") || (person_signed_in? && current_person.starred?(organization.id)) %>
        <%= render partial: 'starred_organizations/filled_star', locals: { organization: } %>
    <% else %>
        <%= render partial: 'starred_organizations/empty_star', locals: { organization: } %>
    <% end %>
<% end %>

app/views/organizations/_search_bar.html.erb
<%= form_with method: :get, url: organizations_path, class: 'mt-4 flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row' do |form| %>
    <div class="w-1/2 px-4 py-2 mt-2 font-semibold bg-gray-300 rounded-lg md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
        <%= form.search_field :organization_name, value: params[:organization_name], placeholder: 'Введите название', class: 'w-full focus:outline-none text-gray-700' %>
    </div>

    <% if !organization_signed_in? %>
        <%= form.checkbox :favorite, { class: 'peer hidden', checked: params[:favorite] == 'true' }, 'true', 'false' %>
        <%= form.label :favorite, 'Избранные', class: 'select-none cursor-pointer rounded-lg border-2 border-gray-400 px-4 py-2 ml-4 font-bold text-gray-600 transition-colors duration-200 ease-in-out peer-checked:bg-indigo-200 peer-checked:text-indigo-900 peer-checked:border-indigo-200' %>
    <% end %>

    <button class="border-2 border-gray-500 px-4 py-2 ml-4 font-semibold bg-transparent rounded-lg hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 focus:outline-none focus:shadow-outline">
        Поиск
    </button>
<% end %>

app/views/organizations/edit.html.erb
<% content_for :title, 'Редактирование организации' %>

<div class="h-full w-full">
  <%= form_with(model: @organization, class: 'h-full items-center contents p-5') do |form| %>
    <% if @organization.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-4 py-2 font-medium rounded-md m-2 mx-auto sm:w-[80%] w-[90%]">
        <h2><%= pluralize(@organization.errors.count, 'error') %>:</h2>

        <ul class="list-disc ml-6">
          <% @organization.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="bg-stone-100 sm:w-[80%] w-[90%] mx-auto p-6">
      <div class="p-5 mt-5">
        <div class="initials flex flex-row justify-around">
          <%= form.label :name, 'Название', class: 'text-xl md:mb-0 mb-1' %>
          <%= form.text_field :name, class: ['bg-white md:w-[35%] w-1/1 px-4 py-2 md:mb-0 mb-3 rounded-xl', { "border-gray-400 focus:outline-blue-600": @organization.errors[:name].none?, "border-2 border-red-400": @organization.errors[:name].any? }] %>

          <%= form.label :activity_field, 'Сфера работы', class: 'text-xl md:mb-0 mb-1' %>
          <%= form.text_field :activity_field, class: ['bg-white md:w-[35%] w-1/1 px-4 py-2 rounded-xl', { "border-gray-400 focus:outline-blue-600": @organization.errors[:activity_field].none?, "border-2 border-red-400": @organization.errors[:activity_field].any? }] %>
        </div>

        <div class="md:p-5 p-1 sm:mt-1 mt-1">
          <div class="mt-5">
            <%= form.label :description, 'Описание', class: 'text-xl' %>
            <%= form.textarea :description, rows: 4, class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @organization.errors[:description].none?, "border-red-400 focus:outline-red-600": @organization.errors[:description].any? }] %>
          </div>

          <div class="mt-5">
            <%= form.label :logo, 'Логотип', class: 'text-xl' %>
            <%= form.file_field :logo, accept: 'image/png,image/gif,image/jpeg', class: ['bg-white w-[100%] px-4 py-2 rounded-xl appearance-none text-heading text-md', { "border-gray-400 focus:outline-blue-600": @organization.errors[:description].none?, "border-red-400 focus:outline-red-600": @organization.errors[:description].any? }] %>
          </div>
        </div>

        <div class="btn mt-2 w-[100%] bg-transparent flex items-center">
          <%= form.submit 'Обновить', class: 'black-btn' %>
          <%= link_to 'Назад', organization_path(@organization), class: 'black-btn' %>
          <%= link_to 'Удалить', @organization, class: 'delete-btn', data: { turbo_confirm: "Вы точно хотите навсегда удалить организацию #{@organization.name} ?", turbo_method: :delete } %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/organizations/index.html.erb
<% content_for :title, 'Организации' %>

<div class="w-full">
  <div class="py-8 sm:py-16 block lg:py-24 relative bg-opacity-50 z-40">

    <div class="relative mx-auto h-full pb-20 md:pb-10 sm:max-w-xl md:max-w-full lg:max-w-screen-xl">
      <div class="mx-auto max-w-7xl relative">
        <div class="max-w-xl mx-auto text-center">
          <div class="inline-flex px-4 py-1.5 mx-auto rounded-full">
            <p class="text-4xl font-semibold tracking-widest text-g uppercase">Организации</p>
          </div>
        </div>

        <div class="flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row">
          <%= render partial: 'search_bar' %>
        </div>

        <div class="grid grid-cols-1 gap-2 mt-12 sm:grid-cols-3 lg:mt-20">
          <%= render partial: 'card', collection: @organizations %>
        </div>
      </div>
    </div>

    <%= render partial: 'layouts/pagy_down_bar' %>
  </div>
</div>

app/views/organizations/show.html.erb
<% content_for :title, @organization.name %>

<div class="w-full">
  <section class=" bg-blue-500ray-50">
    <div class="py-8 sm:py-16 block lg:py-24 relative bg-opacity-50 z-40">

      <div class="relative mx-auto h-full px-4 pb-20 md:pb-10 sm:max-w-xl md:max-w-full md:px-24">

        <div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8 relative">
          <div class="grid grid-cols-2 gap-20">
            <div class="max-w-xl mx-auto text-center">
              <div class="inline-flex px-4 py-1.5 mx-auto rounded-full">
                <p class="text-4xl font-semibold tracking-widest text-g"><%= @organization.name %></p>

                <%= render partial: 'labels', locals: { organization: @organization } %>
              </div>

              <p class="mt-4 text-base leading-relaxed text-gray-600 group-hover:text-white">
                <%= @organization.activity_field %>
              </p>
              <p class="my-4 text-base leading-relaxed text-gray-600 group-hover:text-white">
                <%= @organization.description %>
              </p>

              <% if organization_signed_in? && current_organization == @organization %>
                <%= render partial: 'buttons', locals: { organization: @organization } %>
              <% end %>
            </div>

            <div>
              <%= image_tag @organization.logo_url %>
            </div>
          </div>

          <div class="max-w-xl mx-auto my-14 text-center">
            <div class="inline-flex px-4 py-1.5 mx-auto rounded-full">
              <p class="text-4xl font-semibold tracking-widest text-g uppercase">Мероприятия</p>
            </div>
          </div>

          <div class="grid grid-cols-1 gap-2 mt-12 sm:grid-cols-3 lg:mt-20">
            <%= render partial: 'events/card', collection: @events %>
          </div>

          <%= render partial: 'layouts/pagy_down_bar' %>
        </div>
      </div>
    </section>
  </div>